language: c
os: linux
addons:
  apt:
    packages: libgmp-dev
compiler:
  - gcc
cache:
  directories:
  - src/java/guava/
env:
  global:
    - FIELD=auto  BIGNUM=auto  SCALAR=auto  ENDOMORPHISM=no  STATICPRECOMPUTATION=yes  ECMULTGENPRECISION=auto  ASM=no  BUILD=check  EXTRAFLAGS=  HOST=  ECDH=no  RECOVERY=no  EXPERIMENTAL=no  JNI=no JNI=no SCHNORRSIG=no
    - GUAVA_URL=https://search.maven.org/remotecontent?filepath=com/google/guava/guava/18.0/guava-18.0.jar GUAVA_JAR=src/java/guava/guava-18.0.jar
matrix:
  fast_finish: true
  include:
    - compiler: gcc
      env:
        - DVALGRIND=1
        - CFLAGS=" -fno-omit-frame-pointer -g"
        - ASM=no BIGNUM=no EXTRAFLAGS="--disable-openssl-tests"
        - EXPERIMENTAL=yes RECOVERY=yes ECDH=yes SCHNORRSIG=yes
        - ENDOMORPHISM=no
        - TESTRUNS=1
      addons:
        apt:
          packages:
            - valgrind
    - compiler: gcc
      env:
        - DVALGRIND=1
        - CFLAGS="-fno-omit-frame-pointer -g"
        - ASM=no BIGNUM=no EXTRAFLAGS="--disable-openssl-tests"
        - EXPERIMENTAL=yes RECOVERY=yes ECDH=yes SCHNORRSIG=yes
        - ENDOMORPHISM=no
        - TESTRUNS=8
      addons:
        apt:
          packages:
            - valgrind
    - compiler: gcc
      env:
        - DVALGRIND=1
        - CFLAGS="-fno-omit-frame-pointer -g"
        - ASM=no BIGNUM=no EXTRAFLAGS="--disable-openssl-tests"
        - EXPERIMENTAL=yes RECOVERY=yes ECDH=yes SCHNORRSIG=yes
        - ENDOMORPHISM=no
        - TESTRUNS=64
      addons:
        apt:
          packages:
            - valgrind

before_install: mkdir -p `dirname $GUAVA_JAR`
install: if [ ! -f $GUAVA_JAR ]; then wget $GUAVA_URL -O $GUAVA_JAR; fi
before_script: ./autogen.sh
script:
 - if [ -n "$HOST" ]; then export USE_HOST="--host=$HOST"; fi
 - if [ "x$HOST" = "xi686-linux-gnu" ]; then export CC="$CC -m32"; fi
 - ./configure --enable-experimental=$EXPERIMENTAL --enable-endomorphism=$ENDOMORPHISM --with-field=$FIELD --with-bignum=$BIGNUM --with-asm=$ASM --with-scalar=$SCALAR --enable-ecmult-static-precomputation=$STATICPRECOMPUTATION --with-ecmult-gen-precision=$ECMULTGENPRECISION --enable-module-ecdh=$ECDH --enable-module-recovery=$RECOVERY --enable-module-schnorrsig=$SCHNORRSIG --enable-jni=$JNI $EXTRAFLAGS $USE_HOST && make -j2 && valgrind --max-stackframe=2500000 ./tests $TESTRUNS && valgrind --max-stackframe=2500000 ./exhaustive-tests
after_script:
    - cat ./config.log
